version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cran_pelago
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  app:
    build: .
    command: rails s -b 0.0.0.0 -p 3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file: .env_compose
    environment:
      - DEV_DATABASE_HOST=db
    depends_on:
      - db
    stdin_open: true
    tty: true
  delayed_job:
    build: .
    command: rake jobs:work
    volumes:
      - .:/app 
    env_file: .env_compose
    environment:
      - DEV_DATABASE_HOST=db
    depends_on:
      - db
    stdin_open: true
    tty: true
